this should pass the version check now

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -57,14 +57,7 @@ jobs:
       - name: 'Determine Artifact Name and Tag'
         id: determine_artifact_name
         run: |
-          # Check if this is a pull request event
-          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
-            # Use the head ref for pull request
-            branch_name="${{ github.event.pull_request.head.ref }}"
-          else
-            # Use the normal ref for branch pushes
-            branch_name=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
-          fi
+          branch_name=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
 
           # Determine artifact name based on the branch
           if [[ "${branch_name}" == feature/* ]]; then
@@ -131,6 +124,21 @@ jobs:
         with:
           role-to-assume: arn:aws:iam::881413588329:role/Pickem_Deployer
           aws-region: us-east-1
+
+      - name: 'Set Lambda Function Name'
+        id: set_lambda_name
+        run: |
+          branch_name=$(echo "${{ github.ref }}" | sed 's|refs/heads/||')
+
+          # Set lambda function name based on branch
+          if [[ "${branch_name}" == feature/* ]]; then
+            echo "AWS_LAMBDA=${{ env.AWS_LAMBDA }}_dev" >> $GITHUB_ENV
+          elif [[ "${branch_name}" == main ]]; then
+            echo "AWS_LAMBDA=${{ env.AWS_LAMBDA }}_prod" >> $GITHUB_ENV
+          else
+            echo "Invalid branch name"
+            exit 1
+          fi
 
       - name: 'Update Lambda Function with S3 Object Name'
         run: |
